Fix issues with plugin reload.
Using 'let' for PLUGIN_INFO/INFO instead of 'var' causes:

  SyntaxError: redeclaration of non-configurable global property
  PLUGIN_INFO/INFO

Cf. :h plugin-documentation which uses 'var' as well.