asdfghjkl.js: Add brackets to multiline function
Fix this error:

    Sourcing file failed: ${HOME}/.vimperator/plugin/asdfghjkl.js:101:
    SyntaxError: expected expression, got keyword 'let'

That was caused by having a multiline expression in a function without
braces.

(Discovered on Firefox 41.0.2 on Mac OS X 10.8 with Vimperator 3.10.1.)